name: colav_protobuf_utils CI/CD
run-name: ${{ github.actor }} is testing colav_protobuf pypi pkg 🚀

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: ["published", "created"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest tests/

      - name: Publish pypi pkg
        if: github.event_name == 'release'
        env:
          PYPI_USERNAME: "__token__"
          PYPI_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}

        run:  twine upload dist/* -u "${PYPI_USERNAME}" -p "${PYPI_PASSWORD}" --non-interactive
